import { createClient } from 'npm:@supabase/supabase-js@2';
import { Resend } from 'npm:resend@4';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type, Authorization, X-Client-Info, Apikey',
};

interface AssessmentData {
  name: string;
  email: string;
  company: string;
  role: string;
  industryChallenge: string;
  strategicPriority: string;
  teamSize: string;
  currentTools: string[];
  biggestPainPoint: string;
}

function generatePersonalizedInsights(data: AssessmentData): string {
  let insights = "PERSONALIZED STRATEGIC INSIGHTS:\n\n";
  
  if (data.industryChallenge.includes('digital')) {
    insights += "🔍 DIGITAL TRANSFORMATION PRIORITY:\n";
    insights += "Your focus on digital challenges aligns with our ICE Strategy framework. Consider implementing our Axeus Platform for streamlined digital operations.\n\n";
  }
  
  if (data.industryChallenge.includes('competition')) {
    insights += "⚡ COMPETITIVE ADVANTAGE OPPORTUNITY:\n";
    insights += "Market competition requires strategic differentiation. Our RESIDS Program can help identify unique value propositions.\n\n";
  }
  
  if (data.teamSize === 'startup') {
    insights += "🚀 STARTUP GROWTH STRATEGY:\n";
    insights += "As a growing startup, focus on scalable systems. Our AI+ framework can automate key processes while maintaining agility.\n\n";
  } else if (data.teamSize === 'enterprise') {
    insights += "🏢 ENTERPRISE OPTIMIZATION:\n";
    insights += "Large organizations benefit from our Triplicity™ Solutions for coordinated strategic execution across departments.\n\n";
  }
  
  insights += "📊 RECOMMENDED NEXT STEPS:\n";
  insights += "1. Conduct a comprehensive strategic audit using our ICE methodology\n";
  insights += "2. Implement pilot programs in your highest-priority areas\n";
  insights += "3. Establish metrics and KPIs for continuous improvement\n\n";
  
  insights += "💡 EXCLUSIVE OFFER:\n";
  insights += "Schedule a complimentary 30-minute strategy consultation to discuss your specific challenges and opportunities.";
  
  return insights;
}

Deno.serve(async (req: Request) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, {
      status: 200,
      headers: corsHeaders,
    });
  }

  try {
    const assessmentData: AssessmentData = await req.json();

    if (!assessmentData.name || !assessmentData.email || !assessmentData.company) {
      throw new Error('Missing required fields: name, email, or company');
    }

    const insights = generatePersonalizedInsights(assessmentData);
    const reportContent = `
STRATEGIC ASSESSMENT REPORT
Generated for: ${assessmentData.name}
Company: ${assessmentData.company}

${insights}

---
This report was generated by The Bison Group's Strategic Assessment Tool.
For a comprehensive analysis, contact us at info@thebisongroup.io
    `;

    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const resendApiKey = Deno.env.get('RESEND_API_KEY');

    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    const { data: assessment, error: dbError } = await supabase
      .from('assessments')
      .insert({
        user_name: assessmentData.name,
        user_email: assessmentData.email,
        company: assessmentData.company,
        role: assessmentData.role || 'Not specified',
        industry: assessmentData.industryChallenge || 'Not specified',
        challenges: assessmentData.industryChallenge ? [assessmentData.industryChallenge] : [],
        strategic_priorities: assessmentData.strategicPriority ? [assessmentData.strategicPriority] : [],
        team_size: assessmentData.teamSize || 'Not specified',
        current_tools: assessmentData.currentTools || [],
        biggest_pain_point: assessmentData.biggestPainPoint || 'Not specified',
        report_content: reportContent,
      })
      .select()
      .maybeSingle();

    if (dbError) {
      throw new Error(`Database error: ${dbError.message}`);
    }

    if (!assessment) {
      throw new Error('Assessment was not created');
    }

    if (resendApiKey) {
      try {
        const resend = new Resend(resendApiKey);

        const userEmailHtml = `
          <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
            <h1 style="color: #dc2626;">Your Strategic Assessment Report is Ready!</h1>
            <p>Hi ${assessmentData.name},</p>
            <p>Thank you for completing The Bison Group's Strategic Assessment. Based on your responses, we've generated personalized insights for ${assessmentData.company}.</p>

            <div style="background-color: #f3f4f6; padding: 20px; border-radius: 8px; margin: 20px 0;">
              <h2 style="margin-top: 0;">Your Report</h2>
              <pre style="white-space: pre-wrap; font-size: 14px;">${insights}</pre>
            </div>

            <h3>What's Next?</h3>
            <ul>
              <li>Review your personalized strategic insights</li>
              <li>Identify immediate implementation opportunities</li>
              <li>Schedule a complimentary consultation with our team</li>
              <li>Explore how our ICE Strategy can transform your business</li>
            </ul>

            <p><strong>Ready to take the next step?</strong></p>
            <p>Contact us at <a href="mailto:info@thebisongroup.io">info@thebisongroup.io</a> to schedule your complimentary 30-minute strategy consultation.</p>

            <hr style="margin: 30px 0; border: none; border-top: 1px solid #e5e7eb;" />
            <p style="color: #6b7280; font-size: 12px;">The Bison Group | Strategic Consultancy<br/>This report was generated based on your assessment responses.</p>
          </div>
        `;

        await resend.emails.send({
          from: 'The Bison Group <noreply@thebisongroup.io>',
          to: assessmentData.email,
          subject: `Your Strategic Assessment Report - ${assessmentData.company}`,
          html: userEmailHtml,
        });

        const notificationEmailHtml = `
          <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
            <h1 style="color: #dc2626;">New Strategic Assessment Submission</h1>

            <h2>Contact Information</h2>
            <ul>
              <li><strong>Name:</strong> ${assessmentData.name}</li>
              <li><strong>Email:</strong> ${assessmentData.email}</li>
              <li><strong>Company:</strong> ${assessmentData.company}</li>
              <li><strong>Role:</strong> ${assessmentData.role}</li>
            </ul>

            <h2>Assessment Details</h2>
            <ul>
              <li><strong>Industry Challenge:</strong> ${assessmentData.industryChallenge}</li>
              <li><strong>Strategic Priority:</strong> ${assessmentData.strategicPriority}</li>
              <li><strong>Team Size:</strong> ${assessmentData.teamSize}</li>
              <li><strong>Current Tools:</strong> ${assessmentData.currentTools.join(', ') || 'None selected'}</li>
              <li><strong>Biggest Pain Point:</strong> ${assessmentData.biggestPainPoint}</li>
            </ul>

            <h2>Generated Report</h2>
            <div style="background-color: #f3f4f6; padding: 20px; border-radius: 8px;">
              <pre style="white-space: pre-wrap; font-size: 14px;">${insights}</pre>
            </div>

            <p style="margin-top: 30px;"><strong>Action Required:</strong> Follow up with this lead within 24 hours for maximum engagement.</p>
          </div>
        `;

        await resend.emails.send({
          from: 'The Bison Group <noreply@thebisongroup.io>',
          to: 'info@thebisongroup.io',
          subject: `New Assessment: ${assessmentData.company} - ${assessmentData.name}`,
          html: notificationEmailHtml,
        });
      } catch (emailError) {
        console.error('Email sending failed, but assessment was saved:', emailError);
      }
    } else {
      console.log('RESEND_API_KEY not configured. Assessment saved but emails not sent.');
    }

    return new Response(
      JSON.stringify({
        success: true,
        message: 'Assessment submitted successfully',
        assessmentId: assessment.id
      }),
      {
        status: 200,
        headers: {
          ...corsHeaders,
          'Content-Type': 'application/json',
        },
      }
    );

  } catch (error) {
    console.error('Error:', error);
    return new Response(
      JSON.stringify({ 
        success: false, 
        error: error instanceof Error ? error.message : 'Unknown error' 
      }),
      {
        status: 500,
        headers: {
          ...corsHeaders,
          'Content-Type': 'application/json',
        },
      }
    );
  }
});
