import React, { useState } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import { Checkbox } from '@/components/ui/checkbox';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Progress } from '@/components/ui/progress';
import { Download, CheckCircle, ArrowRight, ArrowLeft } from 'lucide-react';

interface LeadMagnetModalProps {
  isOpen: boolean;
  onClose: () => void;
}

interface SurveyData {
  name: string;
  email: string;
  company: string;
  role: string;
  industryChallenge: string;
  strategicPriority: string;
  teamSize: string;
  currentTools: string[];
  biggestPainPoint: string;
}

export default function LeadMagnetModal({ isOpen, onClose }: LeadMagnetModalProps) {
  const [step, setStep] = useState(1);
  const [isSubmitted, setIsSubmitted] = useState(false);
  const [surveyData, setSurveyData] = useState<SurveyData>({
    name: '',
    email: '',
    company: '',
    role: '',
    industryChallenge: '',
    strategicPriority: '',
    teamSize: '',
    currentTools: [],
    biggestPainPoint: ''
  });

  const totalSteps = 4;
  const progress = (step / totalSteps) * 100;

  const handleInputChange = (field: keyof SurveyData, value: string | string[]) => {
    setSurveyData(prev => ({ ...prev, [field]: value }));
  };

  const handleToolToggle = (tool: string) => {
    setSurveyData(prev => ({
      ...prev,
      currentTools: prev.currentTools.includes(tool)
        ? prev.currentTools.filter(t => t !== tool)
        : [...prev.currentTools, tool]
    }));
  };

  const handleSubmit = async () => {
    try {
      const apiUrl = `${import.meta.env.VITE_SUPABASE_URL}/functions/v1/submit-assessment`;

      const response = await fetch(apiUrl, {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${import.meta.env.VITE_SUPABASE_ANON_KEY}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(surveyData),
      });

      const responseText = await response.text();

      let result;
      try {
        result = responseText ? JSON.parse(responseText) : {};
      } catch (parseError) {
        console.error('JSON parse error:', parseError, 'Response text:', responseText);
        throw new Error(`Invalid response from server. Status: ${response.status}`);
      }

      if (!response.ok || !result.success) {
        const errorMsg = result.error || `Server error (${response.status})`;
        console.error('Assessment submission error:', errorMsg);
        throw new Error(errorMsg);
      }

      setIsSubmitted(true);
    } catch (error) {
      console.error('Error submitting assessment:', error);
      const errorMessage = error instanceof Error ? error.message : 'Unknown error occurred';
      alert(`There was an error submitting your assessment: ${errorMessage}\n\nPlease try again or contact support@thebisongroup.io`);
    }
  };

  const downloadReport = () => {
    // Generate personalized insights based on survey responses
    const insights = generatePersonalizedInsights(surveyData);
    
    // Create and download PDF-like content (simplified version)
    const reportContent = `
STRATEGIC ASSESSMENT REPORT
Generated for: ${surveyData.name}
Company: ${surveyData.company}

${insights}

---
This report was generated by The Bison Group's Strategic Assessment Tool.
For a comprehensive analysis, contact us at info@thebisongroup.io
    `;
    
    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Strategic-Assessment-${surveyData.company || 'Report'}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const generatePersonalizedInsights = (data: SurveyData) => {
    let insights = "PERSONALIZED STRATEGIC INSIGHTS:\n\n";
    
    // Industry-specific insights
    if (data.industryChallenge.includes('digital')) {
      insights += "🔍 DIGITAL TRANSFORMATION PRIORITY:\n";
      insights += "Your focus on digital challenges aligns with our ICE Strategy framework. Consider implementing our Axeus Platform for streamlined digital operations.\n\n";
    }
    
    if (data.industryChallenge.includes('competition')) {
      insights += "⚡ COMPETITIVE ADVANTAGE OPPORTUNITY:\n";
      insights += "Market competition requires strategic differentiation. Our RESIDS Program can help identify unique value propositions.\n\n";
    }
    
    // Team size insights
    if (data.teamSize === 'startup') {
      insights += "🚀 STARTUP GROWTH STRATEGY:\n";
      insights += "As a growing startup, focus on scalable systems. Our AI+ framework can automate key processes while maintaining agility.\n\n";
    } else if (data.teamSize === 'enterprise') {
      insights += "🏢 ENTERPRISE OPTIMIZATION:\n";
      insights += "Large organizations benefit from our Triplicity™ Solutions for coordinated strategic execution across departments.\n\n";
    }
    
    // Strategic priority insights
    insights += "📊 RECOMMENDED NEXT STEPS:\n";
    insights += "1. Conduct a comprehensive strategic audit using our ICE methodology\n";
    insights += "2. Implement pilot programs in your highest-priority areas\n";
    insights += "3. Establish metrics and KPIs for continuous improvement\n\n";
    
    insights += "💡 EXCLUSIVE OFFER:\n";
    insights += "Schedule a complimentary 30-minute strategy consultation to discuss your specific challenges and opportunities.\n";
    
    return insights;
  };

  if (isSubmitted) {
    return (
      <Dialog open={isOpen} onOpenChange={onClose}>
        <DialogContent className="max-w-2xl">
          <div className="text-center py-8">
            <CheckCircle className="mx-auto mb-4 h-16 w-16 text-green-500" />
            <h2 className="text-2xl font-bold mb-4">Your Strategic Assessment is Ready!</h2>
            <p className="text-muted-foreground mb-6">
              Based on your responses, we've generated personalized insights for {surveyData.company}.
            </p>
            
            <div className="space-y-4">
              <Button onClick={downloadReport} className="w-full" size="lg">
                <Download className="mr-2 h-4 w-4" />
                Download Your Strategic Assessment Report
              </Button>
              
              <Card className="text-left">
                <CardHeader>
                  <CardTitle className="text-lg">What's Next?</CardTitle>
                </CardHeader>
                <CardContent>
                  <ul className="space-y-2 text-sm">
                    <li>• Review your personalized strategic insights</li>
                    <li>• Identify immediate implementation opportunities</li>
                    <li>• Schedule a complimentary consultation with our team</li>
                    <li>• Explore how our ICE Strategy can transform your business</li>
                  </ul>
                  
                  <Button className="w-full mt-4" variant="outline">
                    Schedule Free Consultation
                  </Button>
                </CardContent>
              </Card>
            </div>
          </div>
        </DialogContent>
      </Dialog>
    );
  }

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="text-2xl">Strategic Assessment Survey</DialogTitle>
          <p className="text-muted-foreground">
            Get personalized insights for your business in just 2 minutes
          </p>
        </DialogHeader>

        <div className="space-y-6">
          <div>
            <div className="flex justify-between text-sm text-muted-foreground mb-2">
              <span>Step {step} of {totalSteps}</span>
              <span>{Math.round(progress)}% Complete</span>
            </div>
            <Progress value={progress} className="h-2" />
          </div>

          {step === 1 && (
            <Card>
              <CardHeader>
                <CardTitle>Let's Get Started</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div>
                  <Label htmlFor="name">Full Name *</Label>
                  <Input
                    id="name"
                    value={surveyData.name}
                    onChange={(e) => handleInputChange('name', e.target.value)}
                    placeholder="Enter your full name"
                  />
                </div>
                
                <div>
                  <Label htmlFor="email">Business Email *</Label>
                  <Input
                    id="email"
                    type="email"
                    value={surveyData.email}
                    onChange={(e) => handleInputChange('email', e.target.value)}
                    placeholder="your.name@company.com"
                  />
                </div>
                
                <div>
                  <Label htmlFor="company">Company Name *</Label>
                  <Input
                    id="company"
                    value={surveyData.company}
                    onChange={(e) => handleInputChange('company', e.target.value)}
                    placeholder="Your company name"
                  />
                </div>
                
                <div>
                  <Label htmlFor="role">Your Role</Label>
                  <RadioGroup
                    value={surveyData.role}
                    onValueChange={(value) => handleInputChange('role', value)}
                  >
                    <div className="flex items-center space-x-2">
                      <RadioGroupItem value="ceo" id="ceo" />
                      <Label htmlFor="ceo">CEO/Founder</Label>
                    </div>
                    <div className="flex items-center space-x-2">
                      <RadioGroupItem value="executive" id="executive" />
                      <Label htmlFor="executive">C-Level Executive</Label>
                    </div>
                    <div className="flex items-center space-x-2">
                      <RadioGroupItem value="director" id="director" />
                      <Label htmlFor="director">Director/VP</Label>
                    </div>
                    <div className="flex items-center space-x-2">
                      <RadioGroupItem value="manager" id="manager" />
                      <Label htmlFor="manager">Manager</Label>
                    </div>
                    <div className="flex items-center space-x-2">
                      <RadioGroupItem value="consultant" id="consultant" />
                      <Label htmlFor="consultant">Consultant</Label>
                    </div>
                  </RadioGroup>
                </div>
              </CardContent>
            </Card>
          )}

          {step === 2 && (
            <Card>
              <CardHeader>
                <CardTitle>Business Challenges</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div>
                  <Label>What's your biggest industry challenge right now?</Label>
                  <RadioGroup
                    value={surveyData.industryChallenge}
                    onValueChange={(value) => handleInputChange('industryChallenge', value)}
                  >
                    <div className="flex items-center space-x-2">
                      <RadioGroupItem value="digital-transformation" id="digital" />
                      <Label htmlFor="digital">Digital transformation</Label>
                    </div>
                    <div className="flex items-center space-x-2">
                      <RadioGroupItem value="market-competition" id="competition" />
                      <Label htmlFor="competition">Increased market competition</Label>
                    </div>
                    <div className="flex items-center space-x-2">
                      <RadioGroupItem value="operational-efficiency" id="efficiency" />
                      <Label htmlFor="efficiency">Operational efficiency</Label>
                    </div>
                    <div className="flex items-center space-x-2">
                      <RadioGroupItem value="talent-retention" id="talent" />
                      <Label htmlFor="talent">Talent acquisition & retention</Label>
                    </div>
                    <div className="flex items-center space-x-2">
                      <RadioGroupItem value="regulatory-compliance" id="compliance" />
                      <Label htmlFor="compliance">Regulatory compliance</Label>
                    </div>
                  </RadioGroup>
                </div>
                
                <div>
                  <Label>What's your top strategic priority for the next 12 months?</Label>
                  <RadioGroup
                    value={surveyData.strategicPriority}
                    onValueChange={(value) => handleInputChange('strategicPriority', value)}
                  >
                    <div className="flex items-center space-x-2">
                      <RadioGroupItem value="growth" id="growth" />
                      <Label htmlFor="growth">Revenue growth</Label>
                    </div>
                    <div className="flex items-center space-x-2">
                      <RadioGroupItem value="optimization" id="optimization" />
                      <Label htmlFor="optimization">Process optimization</Label>
                    </div>
                    <div className="flex items-center space-x-2">
                      <RadioGroupItem value="innovation" id="innovation" />
                      <Label htmlFor="innovation">Innovation & R&D</Label>
                    </div>
                    <div className="flex items-center space-x-2">
                      <RadioGroupItem value="expansion" id="expansion" />
                      <Label htmlFor="expansion">Market expansion</Label>
                    </div>
                    <div className="flex items-center space-x-2">
                      <RadioGroupItem value="sustainability" id="sustainability" />
                      <Label htmlFor="sustainability">Sustainability initiatives</Label>
                    </div>
                  </RadioGroup>
                </div>
              </CardContent>
            </Card>
          )}

          {step === 3 && (
            <Card>
              <CardHeader>
                <CardTitle>Organization Details</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div>
                  <Label>What's your organization size?</Label>
                  <RadioGroup
                    value={surveyData.teamSize}
                    onValueChange={(value) => handleInputChange('teamSize', value)}
                  >
                    <div className="flex items-center space-x-2">
                      <RadioGroupItem value="startup" id="startup" />
                      <Label htmlFor="startup">Startup (1-50 employees)</Label>
                    </div>
                    <div className="flex items-center space-x-2">
                      <RadioGroupItem value="smb" id="smb" />
                      <Label htmlFor="smb">Small-Medium Business (51-500)</Label>
                    </div>
                    <div className="flex items-center space-x-2">
                      <RadioGroupItem value="enterprise" id="enterprise" />
                      <Label htmlFor="enterprise">Enterprise (500+ employees)</Label>
                    </div>
                  </RadioGroup>
                </div>
                
                <div>
                  <Label>Which tools/systems are you currently using? (Select all that apply)</Label>
                  <div className="grid grid-cols-2 gap-2 mt-2">
                    {['CRM Systems', 'ERP Software', 'Project Management', 'Business Intelligence', 'AI/ML Tools', 'Custom Software'].map((tool) => (
                      <div key={tool} className="flex items-center space-x-2">
                        <Checkbox
                          id={tool}
                          checked={surveyData.currentTools.includes(tool)}
                          onCheckedChange={() => handleToolToggle(tool)}
                        />
                        <Label htmlFor={tool} className="text-sm">{tool}</Label>
                      </div>
                    ))}
                  </div>
                </div>
              </CardContent>
            </Card>
          )}

          {step === 4 && (
            <Card>
              <CardHeader>
                <CardTitle>Final Question</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div>
                  <Label>What's the biggest pain point preventing your organization from reaching its full potential?</Label>
                  <RadioGroup
                    value={surveyData.biggestPainPoint}
                    onValueChange={(value) => handleInputChange('biggestPainPoint', value)}
                  >
                    <div className="flex items-center space-x-2">
                      <RadioGroupItem value="lack-of-strategy" id="strategy" />
                      <Label htmlFor="strategy">Lack of clear strategic direction</Label>
                    </div>
                    <div className="flex items-center space-x-2">
                      <RadioGroupItem value="poor-execution" id="execution" />
                      <Label htmlFor="execution">Poor execution of existing plans</Label>
                    </div>
                    <div className="flex items-center space-x-2">
                      <RadioGroupItem value="resource-constraints" id="resources" />
                      <Label htmlFor="resources">Limited resources or budget</Label>
                    </div>
                    <div className="flex items-center space-x-2">
                      <RadioGroupItem value="technology-gaps" id="technology" />
                      <Label htmlFor="technology">Technology and system limitations</Label>
                    </div>
                    <div className="flex items-center space-x-2">
                      <RadioGroupItem value="market-uncertainty" id="market" />
                      <Label htmlFor="market">Market uncertainty and volatility</Label>
                    </div>
                  </RadioGroup>
                </div>
                
                <div className="bg-blue-50 p-4 rounded-lg">
                  <h4 className="font-semibold mb-2">What You'll Receive:</h4>
                  <ul className="text-sm space-y-1">
                    <li>• Personalized strategic assessment report</li>
                    <li>• Industry-specific recommendations</li>
                    <li>• Implementation roadmap suggestions</li>
                    <li>• Complimentary consultation opportunity</li>
                  </ul>
                </div>
              </CardContent>
            </Card>
          )}

          <div className="flex justify-between">
            {step > 1 && (
              <Button
                variant="outline"
                onClick={() => setStep(step - 1)}
              >
                <ArrowLeft className="mr-2 h-4 w-4" />
                Previous
              </Button>
            )}
            
            <div className="ml-auto">
              {step < totalSteps ? (
                <Button
                  onClick={() => setStep(step + 1)}
                  disabled={
                    (step === 1 && (!surveyData.name || !surveyData.email || !surveyData.company)) ||
                    (step === 2 && (!surveyData.industryChallenge || !surveyData.strategicPriority)) ||
                    (step === 3 && !surveyData.teamSize) ||
                    (step === 4 && !surveyData.biggestPainPoint)
                  }
                >
                  Next
                  <ArrowRight className="ml-2 h-4 w-4" />
                </Button>
              ) : (
                <Button
                  onClick={handleSubmit}
                  disabled={!surveyData.biggestPainPoint}
                  className="bg-[#355E3B] hover:bg-[#355E3B]/90 text-white"
                >
                  Generate My Strategic Assessment
                </Button>
              )}
            </div>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}